version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm: "
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
